default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: testify

development:
  <<: *default

test:
  <<: *default
  database: testify_test

production:
  <<: *default
