# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 887a7aa27918d879ffd35fdfdacb4f92ed5d615ba28203bafc0856e98c713d1c29e0ec20aadeb8fc716fd4c317094a84a434817aeabd8a0399706b68e6340a50

test:
  secret_key_base: d7fc93d1d056a3fe6b2c22e5c808962e4e238e15f39d28b8a6c59fb908aa83ef8850fa88285325c92f1ea02afcc03745d88311d3a8a50b2eacc458aaa19fd19d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
